services:
  lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: .
    deploy:
      replicas: 2
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      - RUST_LOG=sana=debug,tower_http=debug
      - NATS_URL=nats://nats:4222
      - DATABASE_URL=postgres://sana_user:sana_password@db:5432/sana_db
      - COOKIE_KEY=70830F18572093B2C1B1FE0239E0276087F746407DD7E84301CC582052BF6D3469FAB2DD1CD3D9CD9CEA32386EAE066664A37BE1134BB4F6BF222E7DA98E0078

  nats:
    image: nats:latest
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: sana_db
      POSTGRES_USER: sana_user
      POSTGRES_PASSWORD: sana_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sana_user -d sana_db"]
      interval: 5s
      timeout: 5s
      retries: 5
