version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - nats
    environment:
      - RUST_LOG=sana=debug,tower_http=debug
      - NATS_URL=nats://nats:4222

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
